customhost = "mydataproject2.cg2am1wqkt6z.us-east-1.rds.amazonaws.com"
customuser = "anusha"
custompass = "anusha2002"
customdb = "mydataproject2"
custombucket = "anushaproject2"
customregion = "us-east-1"
